import { Case } from "@/types/types";

export const casesData: Case[] = [
  {
    id: "1",
    title: "Potential Threat From Frequent “After Hour Login",
    riskStatus: "high",
    riskScore: 72,
    caseDateTime: "21 Jan 2024, 2:30pm",
    assignee: "Chris Tan",
    assignedDateTime: "21 Jan 2024, 3:00pm",
  },
  {
    id: "2",
    title: "The Potential Threat From Frequent “After Hour Login",
    riskStatus: "high",
    riskScore: 69,
    caseDateTime: "23 Jan 2024, 8:30pm",
    assignee: "Chris Tan",
    assignedDateTime: "25 Jan 2024, 5:00pm",
  },
  {
    id: "3",
    title: "The Potential Threat From Frequent “After Hour Login",
    riskStatus: "high",
    riskScore: 8,
    caseDateTime: "23 Jan 2024, 8:30pm",
    assignee: "John Doe",
    assignedDateTime: "25 Jan 2024, 5:00pm",
  },
  {
    id: "4",
    title: "The Potential Threat From Frequent “After Hour Login",
    riskStatus: "high",
    riskScore: 8,
    caseDateTime: "23 Jan 2024, 8:30pm",
    assignee: "Chris Tan",
    assignedDateTime: "25 Jan 2024, 5:00pm",
  },
  {
    id: "5",
    title: "The Potential Threat From Frequent “After Hour Login",
    riskStatus: "high",
    riskScore: 8,
    caseDateTime: "23 Jan 2024, 8:30pm",
    assignee: "Chris Tan",
    assignedDateTime: "25 Jan 2024, 5:00pm",
  },
  {
    id: "6",
    title: "The Potential Threat From Frequent “After Hour Login",
    riskStatus: "high",
    riskScore: 8,
    caseDateTime: "23 Jan 2024, 8:30pm",
    assignee: "Chris Tan",
    assignedDateTime: "25 Jan 2024, 5:00pm",
  },
  {
    id: "7",
    title: "The Potential Threat From Frequent “After Hour Login",
    riskStatus: "high",
    riskScore: 8,
    caseDateTime: "23 Jan 2024, 8:30pm",
    assignee: "Chris Tan",
    assignedDateTime: "25 Jan 2024, 5:00pm",
  },
  {
    id: "8",
    title: "The Potential Threat From Frequent “After Hour Login",
    riskStatus: "high",
    riskScore: 8,
    caseDateTime: "23 Jan 2024, 8:30pm",
    assignee: "John Doe",
    assignedDateTime: "25 Jan 2024, 5:00pm",
  },
  {
    id: "9",
    title: "The Potential Threat From Frequent “After Hour Login",
    riskStatus: "high",
    riskScore: 8,
    caseDateTime: "23 Jan 2024, 8:30pm",
    assignee: "Chris Tan",
    assignedDateTime: "25 Jan 2024, 5:00pm",
  },
  {
    id: "10",
    title: "The Potential Threat From Frequent “After Hour Login",
    riskStatus: "high",
    riskScore: 8,
    caseDateTime: "23 Jan 2024, 8:30pm",
    assignee: "Chris Tan",
    assignedDateTime: "25 Jan 2024, 5:00pm",
  },
  {
    id: "11",
    title: "The Potential Threat From Frequent “After Hour Login",
    riskStatus: "high",
    riskScore: 8,
    caseDateTime: "23 Jan 2024, 8:30pm",
    assignee: "Chris Tan",
    assignedDateTime: "25 Jan 2024, 5:00pm",
  },
];
